displayName=Sidebar Manager
author=TechDoggo (You Blinked)
description=Customize and organize the RuneLite sidebar
tags=sidebar,ui,customization,icons
version=1.0.0
plugins=com.geeta.sidebarmanager.SidebarManagerPlugin
build=standard